name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Backend (Go)
        - Frontend (React)
        - Docker/Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - OS: 
        - Browser: 
        - Deployment: Docker / Local

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
